#!/bin/bash
sudo /usr/bin/python -u /home/ubuntu/fiware_validator/validator_api/manage.py runserver 0.0.0.0:4042
